import json

old_posts = [
  {
    "id": 1,
    "category": "Salud",
    "title": "Regeneración Dental: El fármaco que hace crecer dientes nuevos",
    "postES": "🦷✨ ¡ADIÓS A LOS IMPLANTES: La ciencia logra regenerar dientes perdidos! ✨🦷\n\nSe ha verificado el inicio de los ensayos clínicos en humanos del primer fármaco capaz de estimular el crecimiento de nuevos dientes. El tratamiento, liderado por la Universidad de Kyoto, utiliza un anticuerpo que bloquea la proteína USAG-1, permitiendo que los 'brotes dentales' inactivos se desarrollen de nuevo.\n\n🔬 Hecho Real: No es ciencia ficción. Tras años de éxito en modelos animales, la medicina regenerativa está a un paso de permitir que los humanos recuperemos piezas dentales de forma natural. Es el descubrimiento más grande en odontología en los últimos 100 años.\n\n📈 Impacto: Millones de personas con agenesia dental o pérdida de dientes podrán recuperar su sonrisa sin necesidad de cirugías invasivas ni materiales artificiales.\n\n💬 SALUD: ¿Te atreverías a probar un fármaco para que te creciera un diente nuevo por elección propia? ¡Comparte tu asombro!\n\n#Salud #MedicinaRegenerativa #Dientes #Innovacion #CienciaReal #Odontologia #Futuro #Bienestar #SaludDental #Descubrimiento",
    "postEN": "🦷✨ TOOTH REGENERATION: The drug that grows new teeth is here! ✨🦷\n\nHuman clinical trials have begun for the world's first drug capable of stimulating new tooth growth. Led by Kyoto University, the treatment blocks the USAG-1 protein, allowing dormant 'tooth buds' to develop. This is the biggest dentistry breakthrough in 100 years. Millions could regain natural teeth without invasive implants or artificial materials. Regenerative medicine is now a reality.\n\n💬 QUESTION: Would you try a drug to grow a new tooth by choice?\n\n#Health #RegenerativeMedicine #Dentistry #Innovation #ScienceFact #FutureHealth #ToothGrowth #MedicalBreakthrough",
    "prompt": "A microscopic view of a translucent, glowing white tooth forming inside a golden biological structure. TITLE: THE DENTAL REBORN."
  },
  {
    "id": 2,
    "category": "Tecnología",
    "title": "El fin de las Apps: Los dispositivos de IA Portátil",
    "postES": "📱❌ ¡LA PRÓXIMA ERA: Rabbit R1 y Humane Pin eliminan la necesidad de apps! ❌📱\n\nSe ha verificado el lanzamiento de los primeros dispositivos de IA 'sin apps' que utilizan Modelos de Acción Grande (LAM). A diferencia de un smartphone, estos gadgets entienden tus intenciones y ejecutan acciones directamente (pedir comida, música, viajes) hablando con la IA sin que abras una sola aplicación.\n\n⚡ Verdad Digital: Estamos pasando de la era del 'clic' a la era del 'intento'. La IA se convierte en tu asistente personal físico que sabe manejar internet por ti. Es el cambio de paradigma más grande desde el lanzamiento del iPhone en 2007.\n\n📈 Mercado: Miles de usuarios ya están probando estos dispositivos que prometen devolvernos el tiempo que perdemos mirando pantallas llenas de iconos.\n\n💬 TECNOLOGÍA: ¿Estás listo para dejar de usar apps y empezar a hablarle a un asistente que haga todo por ti? ¡Dinos tu opinión!\n\n#Tecnologia #RabbitR1 #IA #HumanePin #Innovacion #Gadgets #FuturoDigital #SinApps #AIRevolution #MundoModerno",
    "postEN": "📱❌ APP-FREE ERA: Rabbit R1 and Humane Pin are replacing your smartphone! ❌📱\n\nThe launch of 'app-less' AI devices using Large Action Models (LAM) is verified. These gadgets understand intent and execute actions directly—booking rides, ordering food—via voice, without opening apps. We are shifting from clicks to intent. It's the biggest paradigm shift since the original iPhone. A physical assistant that manages the internet for you is now here.\n\n💬 QUESTION: Are you ready to stop using apps and start talking to an AI assistant instead?\n\n#Technology #RabbitR1 #AI #Innovation #FutureTech #AppLess #GadgetNews #AIRevolution",
    "prompt": "A sleek orange handheld device with a small rotating camera glowing with a soft white ring. TITLE: THE APP KILLER."
  },
  {
    "id": 3,
    "category": "Moda",
    "title": "Adobe Primrose: El Vestido que cambia de Color",
    "postES": "👗✨ ¡MODA MÁGICA: Adobe presenta el vestido que se diseña a sí mismo! ✨👗\n\nSe ha verificado el éxito de 'Project Primrose' de Adobe, un vestido interactivo compuesto por 'módulos de cristal líquido reflectante' que pueden cambiar de patrón y color en un segundo según el movimiento de quien lo lleva o con un simple clic.\n\n🌈 Tecnología Textil: No es una pantalla, es tejido inteligente que permite a los diseñadores crear prendas animadas y dinámicas. La moda deja de ser estática para convertirse en una forma de arte digital fluido que se viste.\n\n📈 Impacto: Imagina tener un solo vestido que puede tener miles de diseños diferentes. Es el futuro de la personalización extrema y el diseño de alta gama interactivo.\n\n💬 ESTILO: ¿Te pondrías un vestido que cambiara de patrón mientras caminas por la calle? ¡Describe tu diseño ideal!\n\n#Moda #AdobePrimrose #TecnoModa #Innovacion #Diseño #Estilo #DigitalFashion #Futuro #Creatividad #ModaInteligente",
    "postEN": "👗✨ MAGIC FASHION: Adobe presents the dress that designs itself! ✨👗\n\nAdobe's 'Project Primrose' is a verified success: an interactive dress using reflective liquid crystal modules that change patterns and colors instantly. Fashion is no longer static; it's fluid digital art you can wear. Imagine one dress with thousands of designs, changing with your movement. The future of extreme personalization and high-end interactive style is now here.\n\n💬 QUESTION: Would you wear a dress that changes its pattern as you walk down the street?\n\n#Fashion #Adobe #Primrose #Innovation #DigitalFashion #StyleFuture #InteractiveDresses #CreativeTech",
    "prompt": "An elegant futuristic dress made of silver scales that are shifting and glowing with floral patterns of light. TITLE: THE LIVING FABRIC."
  },
  {
    "id": 4,
    "category": "Moda",
    "title": "Zapatillas 3D Reciclables: El Futuro de Zellerfeld",
    "postES": "👟♻️ ¡MODA CIRCULAR: Ya puedes imprimir tus zapatillas y devolverlas para reciclarlas! 👟♻️\n\nMarcas como Zellerfeld han verificado el éxito de la fabricación de calzado 3D sin costuras ni pegamentos. Estas zapatillas se imprimen a medida de tu pie y, cuando se gastan, puedes enviarlas de vuelta para que sean trituradas y convertidas en un par nuevo instantáneamente.\n\n🌱 Hecho Sostenible: Este modelo elimina el desperdicio textil y las cadenas de suministro masivas. Es calzado personalizado, ultra cómodo y 100% circular. El concepto de 'basura' desaparece en el mundo del calzado deportivo.\n\n📈 Innovación: La tecnología permite diseños orgánicos que antes eran imposibles de fabricar con métodos tradicionales, mejorando la ergonomía y el rendimiento.\n\n💬 CONSUMO: ¿Comprarías calzado que pudieras 'actualizar' cada año reciclando el material del par anterior? ¡Únete a la moda verde!\n\n#ModaSostenible #Zellerfeld #Impresion3D #EconomiaCircular #Zapatillas #EcoModa #Innovacion #FuturoVerde #DiseñoErgonomico #Reciclaje",
    "postEN": "👟♻️ CIRCULAR FASHION: Print your shoes and send them back to recycle! 👟♻️\n\nBrands like Zellerfeld verified the success of 3D-printed, seamless footwear. Printed exactly to your foot measurements with no glue, they can be fully recycled into new pairs when worn out. This model eliminates textile waste and mass supply chains. Personalized, ultra-comfortable, and 100% circular. 'Trash' is gone from the sports shoe world.\n\n💬 QUESTION: Would you buy shoes that you could 'update' every year by recycling the previous pair?\n\n#SustainableFashion #Zellerfeld #3DPrinting #CircularEconomy #Innovation #EcoShoes #Recycling #FutureStyle",
    "prompt": "A high-tech 3D printer head creating an intricate, honeycombed white sneaker out of glowing polymer. TITLE: THE PRINTED STEP."
  },
  {
    "id": 5,
    "category": "Espacio",
    "title": "Agua en Exoplanetas: El hallazgo de GJ 9827 d",
    "postES": "🌌💧 ¡MISTERIO CÓSMICO: Hallan vapor de agua en la atmósfera de un planeta pequeño! 💧🌌\n\nEl Telescopio Hubble ha verificado la presencia de vapor de agua en el exoplaneta GJ 9827 d. Es el planeta más pequeño fuera de nuestro sistema solar donde se ha detectado una atmósfera rica en agua, lo que sugiere que los 'mundos acuáticos' podrían ser comunes en la galaxia.\n\n🔭 Ciencia Real: Aunque es un planeta caliente (400°C), este hallazgo es crucial para entender cómo se forman las atmósferas en planetas rocosos similares a la Tierra. Estamos refinando nuestra capacidad para detectar mundos habitables.\n\n✨ Exploración: Cada dato nos acerca más a responder si el agua —y la vida— son la norma y no la excepción en el universo.\n\n💬 UNIVERSO: ¿Crees que estamos cerca de encontrar un planeta exactamente igual a la Tierra en otra estrella? ¡Dinos tu opinión!\n\n#Espacio #NASA #Exoplanetas #Agua #Universo #Descubrimiento #Hubble #Ciencia #Astronomia #VidaExtraterrestre",
    "postEN": "🌌💧 COSMIC MYSTERY: Water vapor found in the atmosphere of a small planet! 💧🌌\n\nHubble verified water vapor on exoplanet GJ 9827 d. It's the smallest planet outside our solar system with a water-rich atmosphere, suggesting 'water worlds' might be common. Though hot (400°C), this is key to understanding rocky planet atmospheres. We are refining our ability to eventually find habitable worlds among the stars.\n\n💬 QUESTION: Do you think we are close to finding an Earth twin in another star system?\n\n#Space #NASA #Exoplanets #WaterWorlds #Universe #Hubble #Discovery #Astronomy #Cosmos",
    "prompt": "A distant glowing blue planet surrounded by a hazy mist of light against a black star-filled background. TITLE: THE WATER WORLD."
  },
  {
    "id": 6,
    "category": "IA",
    "title": "Sora: La IA que crea Realidad en Video",
    "postES": "🎬🤖 ¡EL FIN DE LOS EFECTOS ESPECIALES: OpenAI presenta Sora y el video realista! 🤖🎬\n\nSe ha verificado el impacto mundial de Sora, la nueva herramienta de IA de OpenAI capaz de generar clips de video de hasta un minuto con una calidad fotográfica y física asombrosamente real a partir de simples instrucciones de texto.\n\n⚡ Verdad Visual: Los videos muestran reflejos, texturas y movimientos de cámara que antes tomaban meses a un equipo de cine. Las fronteras entre lo real y lo generado por computadora han desaparecido oficialmente.\n\n📈 Impacto Industrial: Desde el cine hasta la publicidad, esta tecnología cambiará cómo consumimos contenido visual para siempre. La creatividad ya no tiene límites técnicos.\n\n💬 CREATIVIDAD: ¿Te da miedo o te emociona vivir en un mundo donde cualquier cosa que imagines se pueda ver como un video real? ¡Cuéntanos!\n\n#IA #Sora #OpenAI #VideoIA #Innovacion #Cine #Tecnologia #FuturoDigital #Creatividad #RealidadVirtual",
    "postEN": "🎬🤖 END OF SPECIAL EFFECTS: OpenAI presents Sora and photorealistic video! 🎬🤖\n\nSora's global impact is verified: OpenAI's new tool generates video clips up to 60 seconds with stunningly realistic physics from simple text prompts. It handles reflections, textures, and complex camera moves that used to take movie studios months. The boundary between real and AI-generated is gone. Cinema and advertising will never be the same.\n\n💬 QUESTION: Does it scare you or excite you to live in a world where anything imagined looks like real video?\n\n#AI #Sora #OpenAI #AIVideo #Innovation #FutureTech #DigitalReality #CinemaAI #Creativity",
    "prompt": "A cinematic shot of a camera lens reflecting a digital nebula of colors and moving images inside it. TITLE: THE ETERNAL EYE."
  },
  {
    "id": 7,
    "category": "Energía",
    "title": "Muros Eólicos: La Escultura que genera Electricidad para tu Casa",
    "postES": "🔋🌪️ ¡ARTE ENERGÉTICO: Los muros de turbinas eólicas que parecen el futuro! 🌪️🔋\n\nSe ha verificado el éxito de 'Wind Turbine Wall', una estructura modular diseñada por Joe Doucet que utiliza cientos de pequeñas turbinas para capturar el viento urbano y generar energía renovable de forma silenciosa y estética.\n\n🌆 Hecho Arquitectónico: A diferencia de las grandes aspas tradicionales, estos muros pueden instalarse en el lateral de edificios o casas, convirtiendo las fachadas en plantas de energía invisibles. Es el matrimonio perfecto entre arte y sostenibilidad.\n\n🌱 Impacto: Un solo muro puede cubrir gran parte de la demanda eléctrica de un hogar promedio, facilitando la independencia energética en entornos urbanos densos.\n\n💬 HOGAR: ¿Instalarías un muro de arte en tu fachada si esto significara que tu luz fuera gratis y limpia? ¡Dinos tu preferencia!\n\n#Energia #Eolica #Innovacion #Arquitectura #Sostenibilidad #Arte #EnergiaLimpia #EcoTecno #FuturoVerde #VivirSostenible",
    "postEN": "🔋🌪️ ENERGY ART: Wind turbine walls that look like the future! 🌪️🔋\n\nThe 'Wind Turbine Wall' modular structure is a verified success. Using hundreds of tiny turbines, it captures urban wind to create silent, aesthetic renewable energy. Unlike traditional turbines, these fit on building facades, turning them into invisible power plants. The perfect marriage of art and sustainability for urban energy independence.\n\n💬 QUESTION: Would you install an art wall on your home if it meant free, clean energy for life?\n\n#Energy #WindTurbines #Innovation #Architecture #Sustainability #ArtTech #CleanPower #EcoDesign #FutureHome",
    "prompt": "A modern house wall made of hundreds of small silver rotating blades reflecting the golden sunset light. TITLE: THE WIND WALL."
  },
  {
    "id": 8,
    "category": "Arqueología",
    "title": "Amazonas: Hallan la Ciudad más Antigua en el Upano",
    "postES": "🌳🏛️ ¡HISTORIA REESCRITA: Detectan una red de ciudades milenarias bajo la selva! 🏛️🌳\n\nMediante tecnología LiDAR (láser), arqueólogos han verificado la existencia de un complejo urbano masivo en el valle del Upano, Ecuador, que data de hace 2,500 años. Es la sociedad urbana más antigua y grande jamás hallada en la cuenca del Amazonas.\n\n🔍 Ciencia: El hallazgo muestra una red sofisticada de calles, plataformas y plazas que conectaban a miles de personas. El Amazonas no era una selva virgen, sino el hogar de civilizaciones avanzadas que manejaban el paisaje con maestría.\n\n🇪🇨 Importancia: Este descubrimiento obliga a los historiadores a repensar todo lo que sabíamos sobre el desarrollo de las culturas precolombinas en Sudamérica.\n\n💬 ASOMBRO: ¿Qué otros secretos crees que siguen ocultos bajo el verde impenetrable de la selva amazónica? ¡Comparte tu teoría!\n\n#Arqueologia #Amazonas #Historia #Descubrimiento #LiDAR #Ecuador #MundoAntiguo #Ciencia #Cultura #Civilizacion",
    "postEN": "🌳🏛️ HISTORY REWRITTEN: Massive network of ancient cities found under the jungle! 🏛️🌳\n\nUsing LiDAR technology, archaeologists verified a massive urban complex in Ecuador's Upano Valley dating back 2,500 years. It's the oldest and largest urban society ever found in the Amazon basin. Sophisticated streets and plazas connected thousands. The Amazon wasn't a virgin jungle; it was home to advanced civilizations mastering the landscape.\n\n💬 QUESTION: What other secrets do you think remain hidden under the deep green Amazon jungle?\n\n#Archaeology #AmazonDiscovery #History #LiDAR #AncientWorlds #Ecuador #Civilization #ScienceDiscovery",
    "prompt": "A bird's eye view of a dense jungle being revealed by a digital laser highlighting geometric ancient structures beneath. TITLE: THE JUNGLE SECRETS."
  },
  {
    "id": 9,
    "category": "Medio Ambiente",
    "title": "Regreso del Olvido: La Abeja Azul de Florida",
    "postES": "🐝💙 ¡MILAGRO DE LA NATURALEZA: Redescubren la abeja azul que se creía extinta! 💙🐝\n\nCientíficos han verificado el redescubrimiento de la 'Abeja Calamintha Azul' en Florida, una especie extremadamente rara que no se había visto en años. Su regreso es un símbolo de esperanza para la biodiversidad y la resiliencia de los ecosistemas locales.\n\n🌿 Hecho verificable: Este insecto depende de un solo tipo de flor para sobrevivir. Los programas de conservación ahora se centran en proteger su hábitat crítico para asegurar que este polinizador único no vuelva a desaparecer.\n\n🔬 Importancia: Cada especie recuperada es una pieza vital del equilibrio de nuestro planeta. El éxito de la conservación nos demuestra que aún estamos a tiempo de proteger nuestra riqueza natural.\n\n💬 ESPERANZA: ¿Cuál es tu animal o insecto favorito que te gustaría ver salvado de la extinción? ¡Comparte tu pasión verde!\n\n#MedioAmbiente #AbejaAzul #Naturaleza #Conservacion #Biodiversidad #Esperanza #Florida #EcoNoticias #Animales #PlanetaLimpio",
    "postEN": "🐝💙 NATURAL MIRACLE: The 'extinct' Blue Bee rediscovered in Florida! 💙🐝\n\nScientists verified the rediscovery of the rare Blue Calamintha Bee in Florida. Believed to be lost, its return is a symbol of hope for biodiversity. This unique pollinator depends on one specific flower type. Conservation programs are now rushing to protect its critical habitat. Every recovered species is a win for our planet's balance.\n\n💬 QUESTION: Which extinct animal would you most like to see saved and returned to nature?\n\n#Environment #BlueBee #Nature #Conservation #Hope #Biodiversity #EcoNews #WildlifeWin",
    "prompt": "An incredibly detailed close-up of a vibrant metallic blue bee resting on a soft violet flower in a sun-drenched field. TITLE: THE BLUE REBIRTH."
  },
  {
    "id": 10,
    "category": "Ciencia Espacial",
    "title": "Motores de Plasma: El viaje orbital de bajo costo",
    "postES": "🚀⚡ ¡ERA ESPACIAL: Los motores de plasma ya impulsan a los satélites pequeños! ⚡🚀\n\nSe ha verificado el éxito de la propulsión eléctrica (motores de plasma) en satélites de tipo CubeSat. A diferencia de los motores químicos pesados, estos sistemas usan campos eléctricos para acelerar iones, permitiendo que los satélites se mantengan en órbita por años con muy poco combustible.\n\n🌠 Hecho Tecnológico: Esta tecnología permite misiones espaciales mucho más baratas y sostenibles, reduciendo la basura espacial al permitir que los satélites se desintegren de forma controlada al final de su vida útil.\n\n🛰️ Impacto: Es la democratización del espacio. Ahora, universidades y pequeñas empresas pueden tener presencia orbital con tecnología de vanguardia y eficiente.\n\n💬 CIENCIA: ¿Te fascina pensar que el plasma —el cuarto estado de la materia— es lo que nos llevará más lejos en el espacio? ¡Opina hoy!\n\n#Espacio #Plasma #Propulsion #Tecnologia #Innovacion #Satélites #CienciaEspacial #NASA #Futuro #Ingenieria",
    "postEN": "🚀⚡ SPACE ERA: Plasma engines are now powering small satellites! ⚡🚀\n\nElectric propulsion (plasma engines) for CubeSats is now a verified success. Unlike heavy chemical rockets, these systems use electric fields to accelerate ions, keeping satellites in orbit for years with minimal fuel. This democratization of space allows universities and small firms to reach orbit sustainably and efficiently, reducing space debris. Plasma is the future of space travel.\n\n💬 QUESTION: Does the idea of plasma—the 4th state of matter—powering our space travel fascinate you?\n\n#Space #PlasmaPropulsion #Technology #Innovation #Satellites #SpaceScience #FutureTravel #Engineering",
    "prompt": "A sleek silver satellite in outer space with a bright violet glow of plasma energy shooting out from its rear. TITLE: THE PLASMA PULSE."
  }
]

with open('new_11.json', 'r', encoding='utf-8') as f:
    new_posts = json.load(f)

full_posts = old_posts + new_posts

with open('posts_content.json', 'w', encoding='utf-8') as f:
    json.dump(full_posts, f, ensure_ascii=False, indent=2)

print("Restored items 1-10 and appended 11-21 successfully into posts_content.json!")
